[build]
  base = "web-app"
  command = "pnpm run build"
  publish = "dist"

[[redirects]]
from = "/api/*"
to = "https://wizallet.onrender.com/api/:splat"
status = 200
force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200